const { FIELD_TYPE } = require('@8base/utils')

const AIRTABLE_FIELD_TYPES = {
  TEXT: 'text',
  MULTILINE_TEXT: 'multilineText',
  MULTIPLE_ATTACHMENT: 'multipleAttachment',
  FOREIGN_KEY: 'foreignKey',
  MULTI_SELECT: 'multiSelect',
  DATE: 'date',
  NUMBER: 'number',
}

const FIELD_TYPE_MAP = {
  [AIRTABLE_FIELD_TYPES.TEXT]: FIELD_TYPE.TEXT,
  [AIRTABLE_FIELD_TYPES.MULTILINE_TEXT]: FIELD_TYPE.TEXT,
  [AIRTABLE_FIELD_TYPES.MULTIPLE_ATTACHMENT]: FIELD_TYPE.FILE,
  [AIRTABLE_FIELD_TYPES.FOREIGN_KEY]: FIELD_TYPE.RELATION,
  [AIRTABLE_FIELD_TYPES.MULTI_SELECT]: FIELD_TYPE.SWITCH,
  [AIRTABLE_FIELD_TYPES.DATE]: FIELD_TYPE.DATE,
  [AIRTABLE_FIELD_TYPES.NUMBER]: FIELD_TYPE.NUMBER,
}

module.exports = {
  AIRTABLE_FIELD_TYPES,
  FIELD_TYPE_MAP,
}
